# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

# renamed to specify backend, but with back, instead of backend
name: record-extraction-app-back
# removed metadata
requiredVersions:
    azd: ">= 1.10.0"
services:
# YUBI: change service name from aca to aca-back to prevent conflicts with other services
  aca-back:
    project: ./src
    language: py
    host: containerapp
    docker:
      remoteBuild: true
hooks:
  postprovision:
    windows:
      shell: pwsh
      run: ./scripts/write_env.ps1
      continueOnError: true
    posix:
      shell: sh
      run: ./scripts/write_env.sh
      continueOnError: true
pipeline:
  variables:
    - AZURE_OPENAI_LOCATION
    - AZURE_OPENAI_MODEL
    - AZURE_OPENAI_MODEL_VERSION
    - AZURE_OPENAI_DEPLOYMENT
    - AZURE_OPENAI_DEPLOYMENT_CAPACITY
    - AZURE_OPENAI_DEPLOYMENT_SKU_NAME
    - AZURE_OPENAI_RESOURCE
    - AZURE_OPENAI_RESOURCE_GROUP
    - AZURE_OPENAI_RESOURCE_GROUP_LOCATION
    - AZURE_OPENAI_SKU_NAME
    - AZURE_OPENAI_API_VERSION
    - CREATE_AZURE_OPENAI
    - AZURE_OPENAI_KEY_FOR_CHATVISION
    - AZURE_OPENAI_ENDPOINT
    - CREATE_ROLE_FOR_USER
    - SERVICE_ACA_RESOURCE_EXISTS
    - DISABLE_KEY_BASED_AUTH